# Generated by Django 5.1 on 2024-08-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_class', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50, unique=True, blank=True))
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('short_desc', models.TextField()),
                ('full_desc', models.TextField()),
                ('image_name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('category', models.ManyToManyField(to='main.category')),
            ],
        ),
    ]
