# Generated by Django 5.1 on 2024-08-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Another',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=70)),
                ('icon_url', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
