# Generated by Django 5.1 on 2024-08-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.CharField(default='None', max_length=60),
        ),
    ]
